name: Run gofmt & unit tests

on:
  push:
    branches:
      - main
    paths:
      - '**/**.go'
  pull_request:
    paths:
      - '**/**.go'
      - 'Makefile'
      - '.github/workflows/quality-checks.yml'

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libnlopt-dev

    - name: Check gofmt
      run: |
        if [ -n "$(gofmt -d .)" ]; then
          echo "gofmt is unhappy with your code quality!! Please run 'make lint' and commit the changes."
          exit 1
        fi

    - name: Run unit tests
      run: make test
